### ISSUE TITLE
在cell上加一个button，喷射的范围只能在cell内部。

### ISSUE THREAD

**Issue by melo30** [LifeForLove/GXUpvoteButton#4]
在cell上加一个button，喷射的范围只能在cell内部。不能延伸到整个controller呢

**Comment by melo30** [comment]
这个问题已解决，办法是：在按钮点击 和 长按时候的地方加一个block回调，在cell里的block实现体里面写self.selected = YES，这样就可以让此时点击的button上的cell处于视图的最上层了。

**Comment by melo30** [comment]
> 这个问题已解决，办法是：在按钮点击 和 长按时候的地方加一个block回调，在cell里的block实现体里面写self.selected = YES，这样就可以让此时点击的button上的cell处于视图的最上层了。

更正一下，上面所说的block回调里面写self.selected = YES并不能保证当前的cell到最上层，将这句改为[self.superview bringSubviewToFront:self]，这样就ok了

**Comment by LifeForLove** [comment]
感谢老哥提供的解决方案，代码已优化，并新增触感反馈功能。
